//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stationary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_notification
    {
        public int not_id { get; set; }
        public string not_action { get; set; }
        public Nullable<System.DateTime> not_date { get; set; }
    }
}
