//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stationary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public tbl_user()
        {
            this.tbl_stationaryRequest = new HashSet<tbl_stationaryRequest>();
        }
    
        public int u_id { get; set; }
        public string u_name { get; set; }
        public string u_email { get; set; }
        public string u_pass { get; set; }
        public string u_grade { get; set; }
        public string u_registernumber { get; set; }
        public string u_location { get; set; }
        public Nullable<int> r_id { get; set; }
    
        public virtual tbl_role tbl_role { get; set; }
        public virtual ICollection<tbl_stationaryRequest> tbl_stationaryRequest { get; set; }
    }
}
