//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stationary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_role
    {
        public tbl_role()
        {
            this.tbl_user = new HashSet<tbl_user>();
        }
    
        public int r_id { get; set; }
        public string r_type { get; set; }
    
        public virtual ICollection<tbl_user> tbl_user { get; set; }
    }
}
