//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stationary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public Nullable<double> p_price { get; set; }
        public Nullable<double> p_qty { get; set; }
        public Nullable<System.DateTime> p_date { get; set; }
        public string p_des { get; set; }
    }
}
